### ISSUE TITLE
[BUG] SplitSeq.py exits abnormally

### ISSUE THREAD

**Issue by vladimirvig** [immcantation/presto#96]
Transferring from the Bitbucket repo...

Hi, I had encountered the following error, while running a pipeline:
`Traceback (most recent call last):
  File "/usr/local/bin/SplitSeq.py", line 851, in <module>
    args.func(**args_dict)
  File "/usr/local/bin/SplitSeq.py", line 486, in sortSeqFile
    if max_count >= rec_count:  max_count = None
       ^^^^^^^^^^^^^^^^^^^^^^
_TypeError: '>=' not supported between instances of 'NoneType' and 'int'_`

Here is the pull request with the fix I had verified to work correctly.
[https://github.com/immcantation/presto/pull/95](https://github.com/immcantation/presto/pull/95)

**Comment by vladimirvig** [comment]
Resolved by a pull request/merge.
https://github.com/immcantation/presto/pull/95/commits/20a7444511306d5d77f3dc37cddfa8815311d09c
